# Generated by Django 5.2.13 on 2026-04-11 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='消息标题')),
                ('content', models.TextField(verbose_name='消息内容')),
                ('message_type', models.CharField(choices=[('price_warning', '价格预警'), ('price_alert', '价格提醒'), ('system', '系统通知'), ('order', '订单通知')], default='system', max_length=20, verbose_name='消息类型')),
                ('priority', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('urgent', '紧急')], default='medium', max_length=10, verbose_name='优先级')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('related_product_id', models.IntegerField(blank=True, null=True, verbose_name='关联产品ID')),
                ('related_product_name', models.CharField(blank=True, max_length=100, verbose_name='关联产品名称')),
                ('price_change_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='价格变动百分比')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='阅读时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_messages', to=settings.AUTH_USER_MODEL, verbose_name='接收用户')),
            ],
            options={
                'verbose_name': '系统消息',
                'verbose_name_plural': '系统消息',
                'db_table': 'system_messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
