# Generated by Django 5.2.13 on 2026-05-30 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_systemmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='是否审核通过'),
        ),
    ]
