# Generated by Django 5.2.13 on 2026-05-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_approve_existing_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemmessage',
            name='change_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='预计天数'),
        ),
        migrations.AddField(
            model_name='systemmessage',
            name='change_direction',
            field=models.CharField(blank=True, choices=[('上涨', '上涨'), ('下跌', '下跌')], max_length=10, null=True, verbose_name='价格变化方向'),
        ),
        migrations.AddField(
            model_name='systemmessage',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='当前价格'),
        ),
        migrations.AddField(
            model_name='systemmessage',
            name='predicted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='预测价格'),
        ),
    ]
