# Generated by Django 4.2.9 on 2026-04-08 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgriculturalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='品名')),
                ('category', models.CharField(choices=[('vegetable', '蔬菜'), ('fruit', '水果'), ('livestock', '畜禽'), ('aquatic', '水产'), ('grain', '粮油'), ('other', '其他')], max_length=20, verbose_name='类别')),
                ('origin', models.CharField(blank=True, max_length=200, verbose_name='产地')),
                ('unit', models.CharField(default='CNY/kg', max_length=20, verbose_name='单位')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '农产品',
                'verbose_name_plural': '农产品',
                'db_table': 'agricultural_products',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('market_name', models.CharField(max_length=200, verbose_name='市场名称')),
                ('avg_price', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='平均价格')),
                ('max_price', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='最高价')),
                ('min_price', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='最低价')),
                ('volume', models.BigIntegerField(blank=True, null=True, verbose_name='交易量')),
                ('source', models.CharField(blank=True, max_length=100, verbose_name='数据来源')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='data_collection.agriculturalproduct', verbose_name='关联产品')),
            ],
            options={
                'verbose_name': '历史价格',
                'verbose_name_plural': '历史价格',
                'db_table': 'price_history',
                'ordering': ['-date', 'market_name'],
                'indexes': [models.Index(fields=['date'], name='price_histo_date_03ce78_idx'), models.Index(fields=['market_name'], name='price_histo_market__d0a997_idx'), models.Index(fields=['product', 'date'], name='price_histo_product_8d104f_idx')],
                'unique_together': {('product', 'market_name', 'date')},
            },
        ),
        migrations.CreateModel(
            name='CleanedPriceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('market_name', models.CharField(max_length=200, verbose_name='市场名称')),
                ('avg_price', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='平均价格')),
                ('max_price', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='最高价')),
                ('min_price', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='最低价')),
                ('volume', models.BigIntegerField(blank=True, null=True, verbose_name='交易量')),
                ('source', models.CharField(blank=True, max_length=100, verbose_name='数据来源')),
                ('is_outlier', models.BooleanField(default=False, verbose_name='是否为异常值')),
                ('outlier_reason', models.CharField(blank=True, max_length=100, verbose_name='异常原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaned_price_data', to='data_collection.agriculturalproduct', verbose_name='关联产品')),
            ],
            options={
                'verbose_name': '清洗后价格',
                'verbose_name_plural': '清洗后价格',
                'db_table': 'cleaned_price_data',
                'ordering': ['-date', 'market_name'],
                'indexes': [models.Index(fields=['date'], name='cleaned_pri_date_484fd4_idx'), models.Index(fields=['market_name'], name='cleaned_pri_market__81a7d8_idx'), models.Index(fields=['product', 'date'], name='cleaned_pri_product_8ad937_idx'), models.Index(fields=['is_outlier'], name='cleaned_pri_is_outl_16a167_idx')],
                'unique_together': {('product', 'market_name', 'date')},
            },
        ),
    ]
