# Generated by Django 4.2.9 on 2026-05-31 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleanedpricedata',
            name='province',
            field=models.CharField(blank=True, max_length=50, verbose_name='省份'),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='province',
            field=models.CharField(blank=True, max_length=50, verbose_name='省份'),
        ),
        migrations.AddIndex(
            model_name='cleanedpricedata',
            index=models.Index(fields=['province'], name='cleaned_pri_provinc_d33301_idx'),
        ),
        migrations.AddIndex(
            model_name='cleanedpricedata',
            index=models.Index(fields=['product', 'province', 'date'], name='cleaned_pri_product_fe46b6_idx'),
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['province'], name='price_histo_provinc_b876fe_idx'),
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['product', 'province', 'date'], name='price_histo_product_aaae71_idx'),
        ),
    ]
