# Generated by Django 5.2.13 on 2026-04-08 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_collection', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_type', models.CharField(choices=[('supply', '供应'), ('demand', '求购')], max_length=10, verbose_name='信息类型')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='数量')),
                ('unit', models.CharField(default='斤', max_length=20, verbose_name='单位')),
                ('expected_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='期望价格(元/斤)')),
                ('origin', models.CharField(blank=True, max_length=200, verbose_name='产地')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('description', models.TextField(blank=True, verbose_name='详细信息')),
                ('status', models.CharField(choices=[('active', '进行中'), ('completed', '已成交'), ('expired', '已过期'), ('cancelled', '已取消')], default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_infos', to='data_collection.agriculturalproduct', verbose_name='农产品')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_infos', to=settings.AUTH_USER_MODEL, verbose_name='发布者')),
            ],
            options={
                'verbose_name': '供需信息',
                'verbose_name_plural': '供需信息',
                'db_table': 'trade_info',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['info_type'], name='trade_info_info_ty_f8acc9_idx'), models.Index(fields=['status'], name='trade_info_status_8f72c0_idx'), models.Index(fields=['product'], name='trade_info_product_2507f7_idx'), models.Index(fields=['created_at'], name='trade_info_created_4241e1_idx')],
            },
        ),
    ]
