# Generated by Django 5.2.13 on 2026-04-11 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0001_initial'),
        ('decision_support', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=32, unique=True, verbose_name='订单编号')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='数量')),
                ('unit', models.CharField(default='斤', max_length=20, verbose_name='单位')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价(元/斤)')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='总金额')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认'), ('shipped', '已发货'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='订单状态')),
                ('buyer_contact', models.CharField(blank=True, max_length=20, verbose_name='买方联系方式')),
                ('seller_contact', models.CharField(blank=True, max_length=20, verbose_name='卖方联系方式')),
                ('delivery_address', models.CharField(blank=True, max_length=200, verbose_name='收货地址')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_orders', to=settings.AUTH_USER_MODEL, verbose_name='买方')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='data_collection.agriculturalproduct', verbose_name='农产品')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_orders', to=settings.AUTH_USER_MODEL, verbose_name='卖方')),
                ('trade_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='decision_support.tradeinfo', verbose_name='关联供需信息')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'db_table': 'order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20, verbose_name='原状态')),
                ('to_status', models.CharField(max_length=20, verbose_name='新状态')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='decision_support.order')),
            ],
            options={
                'verbose_name': '订单状态日志',
                'verbose_name_plural': '订单状态日志',
                'db_table': 'order_status_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_no'], name='order_order_n_4c2cc7_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['buyer'], name='order_buyer_i_8ea383_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['seller'], name='order_seller__9610bf_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='order_status_35c31c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='order_created_6dbd10_idx'),
        ),
    ]
